# Generated by Django 2.2.4 on 2019-08-06 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJudge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='create_date',
        ),
        migrations.AddField(
            model_name='user',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
