# Generated by Django 2.2.4 on 2019-08-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJudge', '0002_auto_20190806_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problemTags',
            field=models.ManyToManyField(to='OnlineJudge.Tag'),
        ),
    ]
