# Generated by Django 2.2.4 on 2019-08-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJudge', '0003_problem_problemtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='participateCourse',
        ),
        migrations.AddField(
            model_name='contest',
            name='participateCourse',
            field=models.ManyToManyField(to='OnlineJudge.Course'),
        ),
    ]
