# Generated by Django 2.2.4 on 2019-08-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJudge', '0004_auto_20190806_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contestName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
