# Generated by Django 2.2.4 on 2019-08-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJudge', '0006_auto_20190806_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitContest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='OnlineJudge.Contest'),
            preserve_default=False,
        ),
    ]
