# Generated by Django 2.2.4 on 2019-08-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJudge', '0007_submission_submitcontest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
