# Generated by Django 2.2.4 on 2019-08-08 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJudge', '0009_auto_20190808_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OnlineJudge.Language'),
        ),
    ]
