# Generated by Django 2.2.4 on 2019-08-08 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJudge', '0010_auto_20190808_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionstatus',
            name='aimSubmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineJudge.Submission'),
        ),
    ]
